### ISSUE TITLE
rz-pipe gives an error saying librz_core.so.0.3.0-git: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by h4x5p4c3** [rizinorg/rz-pipe#19]
my setup:
```
[h4x5p4c3@int3r5t3ll4r ~]$ rizin -v
rizin 0.3.0-git @ linux-x86-64
commit: 899483566d4f25c91178b8ef6ebd72e4872a1222, build: 2021-05-01__01:14:48
[h4x5p4c3@int3r5t3ll4r ~]$ pip install rzpipe
Defaulting to user installation because normal site-packages is not writeable
Collecting rzpipe
  Using cached rzpipe-0.1.0-py3-none-any.whl (11 kB)
Installing collected packages: rzpipe
Successfully installed rzpipe-0.1.0
[h4x5p4c3@int3r5t3ll4r ~]$ python
Python 3.9.4 (default, Apr 20 2021, 15:51:38)
[GCC 10.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import rzpipe
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/h4x5p4c3/.local/lib/python3.9/site-packages/rzpipe/__init__.py", line 38, in <module>
    from .open_sync import open
  File "/home/h4x5p4c3/.local/lib/python3.9/site-packages/rzpipe/open_sync.py", line 16, in <module>
    from .open_base import OpenBase
  File "/home/h4x5p4c3/.local/lib/python3.9/site-packages/rzpipe/open_base.py", line 22, in <module>
    from .native import RCore
  File "/home/h4x5p4c3/.local/lib/python3.9/site-packages/rzpipe/native.py", line 25, in <module>
    lib = CDLL(lib_name)
  File "/usr/lib/python3.9/ctypes/__init__.py", line 374, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: librz_core.so.0.3.0-git: cannot open shared object file: No such file or directory
```

**Comment by h4x5p4c3** [comment]
sorry this error was due to improper path
